/*************************************************************************************
   
   Toolkit for WPF

   Copyright (C) 2007-2024 Xceed Software Inc.

   This program is provided to you under the terms of the XCEED SOFTWARE, INC.
   COMMUNITY LICENSE AGREEMENT (for non-commercial use) as published at 
   https://github.com/xceedsoftware/wpftoolkit/blob/master/license.md 

   For more features, controls, and fast professional support,
   pick up the Plus Edition at https://xceed.com/xceed-toolkit-plus-for-wpf/

   Stay informed: follow @datagrid on Twitter or Like http://facebook.com/datagrids

  ***********************************************************************************/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xceed.Wpf.Toolkit.LiveExplorer.Samples.PropertyGrid.Views {
    using System;


    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayLocalizationRes {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayLocalizationRes() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xceed.Wpf.Toolkit.LiveExplorer.Samples.PropertyGrid.Views.DisplayLocalizationRes", typeof(DisplayLocalizationRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string DetailsCategory {
            get {
                return ResourceManager.GetString("DetailsCategory", resourceCulture);
            }
        }

        internal static string FavoriteActor1 {
            get {
                return ResourceManager.GetString("FavoriteActor1", resourceCulture);
            }
        }

        internal static string FavoriteActor1Desc {
            get {
                return ResourceManager.GetString("FavoriteActor1Desc", resourceCulture);
            }
        }

        internal static string FavoriteActor2 {
            get {
                return ResourceManager.GetString("FavoriteActor2", resourceCulture);
            }
        }

        internal static string FavoriteActor2Desc {
            get {
                return ResourceManager.GetString("FavoriteActor2Desc", resourceCulture);
            }
        }

        internal static string FavoriteActor3 {
            get {
                return ResourceManager.GetString("FavoriteActor3", resourceCulture);
            }
        }

        internal static string FavoriteActor3Desc {
            get {
                return ResourceManager.GetString("FavoriteActor3Desc", resourceCulture);
            }
        }

        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }

        internal static string FirstNameDesc {
            get {
                return ResourceManager.GetString("FirstNameDesc", resourceCulture);
            }
        }

        internal static string InfoCategory {
            get {
                return ResourceManager.GetString("InfoCategory", resourceCulture);
            }
        }

        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }

        internal static string LastNameDesc {
            get {
                return ResourceManager.GetString("LastNameDesc", resourceCulture);
            }
        }

        internal static string NotListed {
            get {
                return ResourceManager.GetString("NotListed", resourceCulture);
            }
        }
    }
}
