//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xceed.Wpf.Toolkit.LiveExplorer.Samples.PropertyGrid.Views {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayLocalizationRes {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayLocalizationRes() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xceed.Wpf.Toolkit.LiveExplorer.Samples.PropertyGrid.Views.DisplayLocalizationRes", typeof(DisplayLocalizationRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DetailsCategory {
            get {
                return ResourceManager.GetString("DetailsCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Favorite actor 1 (no DisplayName).
        /// </summary>
        internal static string FavoriteActor1 {
            get {
                return ResourceManager.GetString("FavoriteActor1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This property&apos;s type is an enum whose values have no DisplayName attributes. These values displayed are provided by the ToString() method..
        /// </summary>
        internal static string FavoriteActor1Desc {
            get {
                return ResourceManager.GetString("FavoriteActor1Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Favorite actor 2 (with DisplayName).
        /// </summary>
        internal static string FavoriteActor2 {
            get {
                return ResourceManager.GetString("FavoriteActor2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This property&apos;s type is an enum whose values are decorated with the ExtendedDisplayName attribute. Combined with the EnumDisplayNameConverter, this allows display values to be customized..
        /// </summary>
        internal static string FavoriteActor2Desc {
            get {
                return ResourceManager.GetString("FavoriteActor2Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Favorite actor 3.
        /// </summary>
        internal static string FavoriteActor3 {
            get {
                return ResourceManager.GetString("FavoriteActor3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;(Not listed)&quot; enum value shows that enum values can also be localized..
        /// </summary>
        internal static string FavoriteActor3Desc {
            get {
                return ResourceManager.GetString("FavoriteActor3Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First name of that person.
        /// </summary>
        internal static string FirstNameDesc {
            get {
                return ResourceManager.GetString("FirstNameDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InfoCategory {
            get {
                return ResourceManager.GetString("InfoCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usually the familly name of the person.
        /// </summary>
        internal static string LastNameDesc {
            get {
                return ResourceManager.GetString("LastNameDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (Not listed).
        /// </summary>
        internal static string NotListed {
            get {
                return ResourceManager.GetString("NotListed", resourceCulture);
            }
        }
    }
}
