//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Controls.DataVisualization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Controls.DataVisualization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the Chart&apos;s Axes property is not supported; changes to the collection should be made with its .Add/.Remove methods instead..
        /// </summary>
        internal static string Chart_Axes_SetterNotSupported {
            get {
                return ResourceManager.GetString("Chart_Axes_SetterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis location cannot be changed to auto when hosted inside of a series host..
        /// </summary>
        internal static string Chart_AxisLocationChanged_CantBeChangedToAutoWhenHostedInsideOfASeriesHost {
            get {
                return ResourceManager.GetString("Chart_AxisLocationChanged_CantBeChangedToAutoWhenHostedInsideOfASeriesHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the Chart&apos;s Series property is not supported; changes to the collection should be made with its .Add/.Remove methods instead..
        /// </summary>
        internal static string Chart_Series_SetterNotSupported {
            get {
                return ResourceManager.GetString("Chart_Series_SetterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content property must be set to a Chart object..
        /// </summary>
        internal static string DataPointSeriesDropTarget_set_Content_ContentMustBeAChart {
            get {
                return ResourceManager.GetString("DataPointSeriesDropTarget_set_Content_ContentMustBeAChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned dependent axis cannot be used. This may be due to an unset Orientation property for the axis or a type mismatch between the values being plotted and those supported by the axis..
        /// </summary>
        internal static string DataPointSeriesWithAxes_GetAxes_AssignedDependentAxisCannotBeUsed {
            get {
                return ResourceManager.GetString("DataPointSeriesWithAxes_GetAxes_AssignedDependentAxisCannotBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned independent axis cannot be used. This may be due to an unset Orientation property for the axis..
        /// </summary>
        internal static string DataPointSeriesWithAxes_GetAxes_AssignedIndependentAxisCannotBeUsed {
            get {
                return ResourceManager.GetString("DataPointSeriesWithAxes_GetAxes_AssignedIndependentAxisCannotBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable axis is available for plotting the dependent value..
        /// </summary>
        internal static string DataPointSeriesWithAxes_NoSuitableAxisAvailableForPlottingDependentValue {
            get {
                return ResourceManager.GetString("DataPointSeriesWithAxes_NoSuitableAxisAvailableForPlottingDependentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This series does not support radial axes..
        /// </summary>
        internal static string DataPointSeriesWithAxes_ThisSeriesDoesNotSupportRadialAxes {
            get {
                return ResourceManager.GetString("DataPointSeriesWithAxes_ThisSeriesDoesNotSupportRadialAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SeriesDefinition does not have its DependentValueBinding or DependentValuePath properties set; unable to determine the source for dependent values. Please use either of these properties to identify the data model property corresponding to the dependent values..
        /// </summary>
        internal static string DefinitionSeries_EnsureAxes_MissingDependentValueBinding {
            get {
                return ResourceManager.GetString("DefinitionSeries_EnsureAxes_MissingDependentValueBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SeriesDefinition does not have its IndependentValueBinding or IndependentValuePath properties set; unable to determine the source for independent values. Please use either of these properties to identify the data model property corresponding to the independent values..
        /// </summary>
        internal static string DefinitionSeries_EnsureAxes_MissingIndependentValueBinding {
            get {
                return ResourceManager.GetString("DefinitionSeries_EnsureAxes_MissingIndependentValueBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the SeriesDefinitions property of a DefinitionSeries is not supported; changes to the collection should be made with its .Add/.Remove methods instead..
        /// </summary>
        internal static string DefinitionSeries_SeriesDefinitions_SetterNotSupported {
            get {
                return ResourceManager.GetString("DefinitionSeries_SeriesDefinitions_SetterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine the size of an axis without an orientation..
        /// </summary>
        internal static string DisplayAxis_GetLength_CannotDetermineTheLengthOfAnAxisWithAnOrientationOfNone {
            get {
                return ResourceManager.GetString("DisplayAxis_GetLength_CannotDetermineTheLengthOfAnAxisWithAnOrientationOfNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to set Edge property to an invalid value..
        /// </summary>
        internal static string EdgePanel_OnEdgePropertyChanged {
            get {
                return ResourceManager.GetString("EdgePanel_OnEdgePropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataRangeBinding property of the Interpolator must be bound to an IConvertible object..
        /// </summary>
        internal static string Interpolator_IncludeInRange_DataRangeBindingNotIConvertible {
            get {
                return ResourceManager.GetString("Interpolator_IncludeInRange_DataRangeBindingNotIConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value must be larger than or equal to the minimum value..
        /// </summary>
        internal static string Range_ctor_MaximumValueMustBeLargerThanOrEqualToMinimumValue {
            get {
                return ResourceManager.GetString("Range_ctor_MaximumValueMustBeLargerThanOrEqualToMinimumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Cannot read the Maximum of an empty range.&quot;.
        /// </summary>
        internal static string Range_get_Maximum_CannotReadTheMaximumOfAnEmptyRange {
            get {
                return ResourceManager.GetString("Range_get_Maximum_CannotReadTheMaximumOfAnEmptyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Cannot read the Minimum of an empty range.&quot;.
        /// </summary>
        internal static string Range_get_Minimum_CannotReadTheMinimumOfAnEmptyRange {
            get {
                return ResourceManager.GetString("Range_get_Minimum_CannotReadTheMinimumOfAnEmptyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}].
        /// </summary>
        internal static string Range_ToString_Data {
            get {
                return ResourceManager.GetString("Range_ToString_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data..
        /// </summary>
        internal static string Range_ToString_NoData {
            get {
                return ResourceManager.GetString("Range_ToString_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value must be larger than or equal to the minimum value..
        /// </summary>
        internal static string RangeAxis_MaximumValueMustBeLargerThanOrEqualToMinimumValue {
            get {
                return ResourceManager.GetString("RangeAxis_MaximumValueMustBeLargerThanOrEqualToMinimumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value must be smaller than or equal to the maximum value..
        /// </summary>
        internal static string RangeAxis_MinimumValueMustBeLargerThanOrEqualToMaximumValue {
            get {
                return ResourceManager.GetString("RangeAxis_MinimumValueMustBeLargerThanOrEqualToMaximumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection is read-only..
        /// </summary>
        internal static string ReadOnlyObservableCollection_CollectionIsReadOnly {
            get {
                return ResourceManager.GetString("ReadOnlyObservableCollection_CollectionIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reset a ResourceDictionaryEnumerator; reset the ResourceDictionaryDispenser instead..
        /// </summary>
        internal static string ResourceDictionaryEnumerator_CantResetEnumeratorResetDispenserInstead {
            get {
                return ResourceManager.GetString("ResourceDictionaryEnumerator_CantResetEnumeratorResetDispenserInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series {0}.
        /// </summary>
        internal static string Series_OnGlobalSeriesIndexPropertyChanged_UntitledSeriesFormatString {
            get {
                return ResourceManager.GetString("Series_OnGlobalSeriesIndexPropertyChanged_UntitledSeriesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A series cannot be added to more than one series host..
        /// </summary>
        internal static string Series_SeriesHost_SeriesHostPropertyNotNull {
            get {
                return ResourceManager.GetString("Series_SeriesHost_SeriesHostPropertyNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SeriesDefinition instance&apos;s SeriesHost property may only be set to an instance of the DefinitionSeries class; other SeriesHost types are not supported..
        /// </summary>
        internal static string SeriesDefinition_SeriesHost_InvalidParent {
            get {
                return ResourceManager.GetString("SeriesDefinition_SeriesHost_InvalidParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to remove permanent axis from axis collection..
        /// </summary>
        internal static string SeriesHostAxesCollection_InvalidAttemptToRemovePermanentAxisFromSeriesHost {
            get {
                return ResourceManager.GetString("SeriesHostAxesCollection_InvalidAttemptToRemovePermanentAxisFromSeriesHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An axis cannot be removed from a series host when one or more hosted series is listening to it..
        /// </summary>
        internal static string SeriesHostAxesCollection_RemoveItem_AxisCannotBeRemovedFromASeriesHostWhenOneOrMoreSeriesAreListeningToIt {
            get {
                return ResourceManager.GetString("SeriesHostAxesCollection_RemoveItem_AxisCannotBeRemovedFromASeriesHostWhenOneOrMo" +
                        "reSeriesAreListeningToIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either ItemTemplate must be set or TreeMapItemDefinitionSelector must return a non-null template..
        /// </summary>
        internal static string TreeMap_BuildTreeMapTree_TemplateNotSet {
            get {
                return ResourceManager.GetString("TreeMap_BuildTreeMapTree_TemplateNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of PropertyBinding property of an interpolator cannot be null..
        /// </summary>
        internal static string TreeMap_CreateChildren_InterpolatorBindingNotSet {
            get {
                return ResourceManager.GetString("TreeMap_CreateChildren_InterpolatorBindingNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the TreeMap&apos;s Interpolators Property is not supported; changes to the collection should be made with its .Add/.Remove methods instead..
        /// </summary>
        internal static string TreeMap_Interpolators_SetterNotSupported {
            get {
                return ResourceManager.GetString("TreeMap_Interpolators_SetterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to insert a duplicate item..
        /// </summary>
        internal static string UniqueObservableCollection_InvalidAttemptToInsertADuplicateItem {
            get {
                return ResourceManager.GetString("UniqueObservableCollection_InvalidAttemptToInsertADuplicateItem", resourceCulture);
            }
        }
    }
}
